### ISSUE TITLE
Closing the last open window doesn't quit the app

### ISSUE THREAD

**Issue by jaydenseric** [pornel/ImageAlpha#18]
Closing the last open window doesn't quit the app. This is inconsistent to the behavior of ImageOptim.

**Comment by pornel** [comment]
It's inconsistent with ImageOptim indeed. However, but both applications follow Apple's design guidelines.

* ImageOptim is a single-window application. The window represents the app, not a document, so closing the window closes the app (e.g. iPhoto, Calendar, Contacts, Photo booth).

* ImageAlpha is a document-oriented app. It can have multiple windows and each window represents a file. Closing the window closes the file (e.g. TextEdit, Keynote, Preview)

**Comment by jaydenseric** [comment]
Thanks for the explanation :)
