### ISSUE TITLE
Massive memory leak

### ISSUE THREAD

**Issue by georgegulyaev** [pornel/ImageAlpha#19]
Hello guys, enjoying your up — it saves a lot of space for my iOS projects.
But looks like you have a huge memory leak. I was optimizing big amount of PNG images today (~600). Each time I drag and drop a new image, the app starts to consume more and more memory. It ends up with 7GB consuming memory per ~300 images I noticed. Looks like some of your objects are not deallocated properly. 
Hope it helps.

Regards,
George G.

**Comment by pornel** [comment]
Sorry. The app is written in Python, which makes Cocoa memory management awkward.

If you're processing lots of images I suggest using pngquant directly or via ImageOptim-CLI wrapper.

**Comment by georgegulyaev** [comment]
Anyway, thanks for your app :)
