### ISSUE TITLE
Unable to start ImageAlpha

### ISSUE THREAD

**Issue by neowinston** [pornel/ImageAlpha#21]
I'm not able to start the program anymore. This is the message I'm getting:

![alpha](https://cloud.githubusercontent.com/assets/231799/9738467/a9124666-5619-11e5-9bcf-271a0e6a5f23.png)

How to fix this issue? Thanks!

**Comment by pornel** [comment]
What's in the cnosole.app?

**Comment by neowinston** [comment]
I don't know why, but compiled from source and it's working. Thanks!

**Comment by pornel** [comment]
It's good to hear that it compiles not only on my machine :)
