### ISSUE TITLE
Why no File → Save option?

### ISSUE THREAD

**Issue by waldoj** [pornel/ImageAlpha#24]
ImageAlpha requires that the file be saved in a multi-step process. That is, a new file must be named, or one must affirmatively agree to overwrite the existing file. It's not possible to simply save the file. In fact, that option is grayed out:

![File menu](https://cloud.githubusercontent.com/assets/656758/11224025/f2dafb40-8d40-11e5-82cc-1fd4b8dcd796.png)

One must choose `Save As`, and choose to overwrite the existing file:

![Save confirmation](https://cloud.githubusercontent.com/assets/656758/11224063/2047029a-8d41-11e5-9824-bfa88ea09ab4.png)

This is a very different process than ImageOptim, which overwrites the existing file silently. I get that ImageOptim is non-interactive, while ImageAlpha requires the user to indicate by how much to simplify the color palette, but I don't see the need to disable `Save`.

I'm not reporting this as a bug, or requesting a feature, but instead just asking: why does ImageAlpha work like this?

**Comment by pornel** [comment]
This is because the operation irreversibly loses quality. I suggest using the tool to save a copy under a new name, without destroying the original.

ImageOptim, at least by default, is lossless, so overwriting of the original file doesn't lose anything of value.

**Comment by waldoj** [comment]
Got it. So this is a well-considered decision (albeit not the decision that I'd prefer) that falls within the realm of opinionated software, which we need more of. :) Thanks!
