### ISSUE TITLE
Batch Processing

### ISSUE THREAD

**Issue by JeffreyTome** [pornel/ImageAlpha#31]
Can you please make a way to simply drag and drop multiple PNG images into ImageAlpha at once to compress? 

I've tried ImageOptim and honestly PNG Gauntlet for PC is a LOT better giving me smaller files sizes and better quality gradations. PNG Gauntlet shows me the % compressed for each and every PNG image. I would like this for ImageAlpha.

Please make this,
Thanks!

**Comment by pornel** [comment]
Lossy mode in ImageOptim uses pngquant, which gives the same compression as ImageAlpha.

Both ImageOptim and PNG Gauntlet use PNGOUT + OptiPNG, so they should give about the same file sizes (PNG Gauntlet also uses DeflOpt, but it's a minor, abandoned tool that adds only about 1% more compression).
