### ISSUE TITLE
Does not work on High Sierra

### ISSUE THREAD

**Issue by kode54** [pornel/ImageAlpha#34]
Instead of opening the document window when attempting to open an image, it instead dumps messages to the system log:

On startup:

```
Jun 15 17:37:03 Christophers-iMac ImageAlpha[2541]: DEPRECATED USE in libdispatch client: Changing the target of a source after it has been activated
```

On Open dialog:

```
Jun 15 17:37:13 Christophers-iMac ImageAlpha[2541]: objc[2541]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/FinderKit (0x1130e3200) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x113552c00). One of the two will be used. Which one is undefined.
Jun 15 17:37:13 Christophers-iMac ImageAlpha[2541]: assertion failed: 17A264c: libxpc.dylib + 73873 [64AE8381-F096-3184-A85C-C50DB8D979E6]: 0x89
```

And on actually opening an image:

```
Jun 15 17:37:19 Christophers-iMac ImageAlpha[2541]: BUG in libdispatch: 17A264c - 2505 - 0x9ed
Jun 15 17:37:21 Christophers-iMac ImageAlpha[2541]: BUG in libdispatch client: kevent[mach_recv] monitored resource vanished before the source cancel handler was invoked
```

**Comment by NSDeveloper** [comment]
V1.4.0 work on High Sierra

**Comment by edwinveldhuizen** [comment]
Here in build 17A306f it still doesn't work

**Comment by pornel** [comment]
The second message comes  from `FIFinderSyncExtensionHost`. ImageAlpha doesn't use that API. It may be coming from a different Dropbox-like app that tries to monitor or badge files in Finder and file dialogs.

As for the other cases — I have no idea. I don't use libdispatch directly. Just high-level NSTask.

I've made a mistake of writing this app in Python, so I have very little control of how it interacts with the system, and it's all up to Apple to keep Python and PyObjC working, which perhaps isn't their priority.

**Comment by pornel** [comment]
I've finally installed High Sierra (gosh, the beta is so buggy).

Fortunately the real cause was not related to the log, but just some unexpected infinite recursion caused by a change of behavior of  PyObjC or Cocoa. So the app lives for another day!

**Comment by round** [comment]
Yay! Is there a mechanism for me to download the compiled version with the fix? 😬

**Comment by pornel** [comment]
The autoupdate should do it.
