### ISSUE TITLE
Imagealpha not working in High Sierra

### ISSUE THREAD

**Issue by magnuslindstaf** [pornel/ImageAlpha#37]
Hi and thank you for a fantastic app – I use it ever day. 

I just upgraded to MacOS High Sierra, and ImageAlpha will no work. The app opens, but will not open the window where the image file usually goes.

Will there be support for High Sierra in the future?

All the best,
Magnus

**Comment by pornel** [comment]
There's an update that fixes the issue: https://pngmini.com/ImageAlpha1.5.1.tar.bz2
